# Generated by Django 6.0.5 on 2026-05-22 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('auth.login', 'Login'), ('auth.logout', 'Logout'), ('navigation.visit', 'Navigation Visit'), ('workflow.start', 'Workflow Start'), ('workflow.progress', 'Workflow Progress'), ('workflow.complete', 'Workflow Complete'), ('recommendation.shown', 'Recommendation Shown'), ('recommendation.clicked', 'Recommendation Clicked'), ('system.error', 'System Error')], max_length=100)),
                ('event_category', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
