# Generated by Django 6.0.5 on 2026-05-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='users.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Curriculum', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='users.institution')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='curriculum.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('PATHWAY', 'Pathway'), ('BRANCH', 'Branch'), ('GROUP', 'Group'), ('SUBJECT_CONTAINER', 'Subject Container')], max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='curriculum.curriculum')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='curriculum.curriculumnode')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_subjects_per_student', models.PositiveIntegerField(default=8)),
                ('min_subjects_per_student', models.PositiveIntegerField(default=7)),
                ('allow_co_curricular', models.BooleanField(default=True)),
                ('max_co_curricular', models.PositiveIntegerField(default=2)),
                ('curriculum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='curriculum.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='curriculum.academiclevel')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_per_week', models.PositiveIntegerField(default=5)),
                ('max_lessons_per_day', models.PositiveIntegerField(default=2)),
                ('allow_double_lessons', models.BooleanField(default=False)),
                ('max_double_lessons_per_week', models.PositiveIntegerField(default=0)),
                ('preferred_consecutive', models.BooleanField(default=False)),
                ('requires_lab', models.BooleanField(default=False)),
                ('requires_projector', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='curriculum.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='NodeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=False)),
                ('is_optional', models.BooleanField(default=True)),
                ('group_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='curriculum.curriculumnode')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_mappings', to='subjects.subject')),
            ],
            options={
                'ordering': ['display_order', 'subject__name'],
                'unique_together': {('node', 'subject')},
            },
        ),
    ]
